#!/bin/bash 

Movies=("RRR" "DJ-till2" "Murari") 

echo "First movies is: : ${Movies[0]}"
echo "second movies is: : ${Movies[1]}"
echo "third  movies is: : ${Movies[2]}" 
``` 
echo "Movies are: : $@6-{Movies}"

